name: Java CI with Maven

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  job2:
    runs-on: ubuntu-latest
    needs: [build]
    name: Docker Compose UP
    steps:
      - uses: actions/checkout@v3
      - run: | 
             cd Demo
             docker compose up
             docker ps -a
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: |
           cd Demo
           mkdir -p files
           mvn package -Dmaven.build.directory=Demo/files/
           mkdir artifacts && cp files/*.jar artifacts
           cd artifacts && ls
    - name: Save artifact 
      uses: actions/upload-artifact@v3
      with:
        name: github-actions-artifact
        path: artifacts/
